"""create etfs securities etf_holdings tables

Revision ID: 141fed803b2f
Revises: 
Create Date: 2026-08-01 19:20:50.737348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141fed803b2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etfs',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=10), nullable=True),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('etf_holdings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('etf_ticker', sa.String(length=10), nullable=False),
    sa.Column('security_ticker', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('covered_weight', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_ticker'], ['etfs.ticker'], ),
    sa.ForeignKeyConstraint(['security_ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etf_holdings')
    op.drop_table('securities')
    op.drop_table('etfs')
    # ### end Alembic commands ###
