"""add macro_observations table

Revision ID: 220303eadd9c
Revises: 8628a49e6886
Create Date: 2026-08-05 18:37:18.177802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220303eadd9c'
down_revision: Union[str, None] = '8628a49e6886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_observations',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('series_code', sa.String(length=20), nullable=False),
    sa.Column('series_name', sa.String(length=200), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('previous_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'observation_date', name='uq_series_obs_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_observations')
    # ### end Alembic commands ###
