"""add filing_embeddings table

Revision ID: 3ca47b4fe878
Revises: 4f011cff873e
Create Date: 2026-08-06 18:20:55.442770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca47b4fe878'
down_revision: Union[str, None] = '4f011cff873e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_embeddings',
    sa.Column('filing_id', sa.String(length=50), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('filing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filing_embeddings')
    # ### end Alembic commands ###
