"""add event classification fields to filings

Revision ID: 4ca2e58b0bdf
Revises: 220303eadd9c
Create Date: 2026-08-06 17:57:25.389299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca2e58b0bdf'
down_revision: Union[str, None] = '220303eadd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('event_category', sa.String(length=30), nullable=True))
    op.add_column('filings', sa.Column('sentiment_label', sa.String(length=10), nullable=True))
    op.add_column('filings', sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('filings', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('filings', sa.Column('embedding_generated', sa.String(length=5), nullable=True))
    op.add_column('filings', sa.Column('processing_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'processing_status')
    op.drop_column('filings', 'embedding_generated')
    op.drop_column('filings', 'content_hash')
    op.drop_column('filings', 'sentiment_score')
    op.drop_column('filings', 'sentiment_label')
    op.drop_column('filings', 'event_category')
    # ### end Alembic commands ###
