"""add filings table

Revision ID: 4ec11981a3d6
Revises: 274f6bf1b0cb
Create Date: 2026-08-05 18:08:22.350435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec11981a3d6'
down_revision: Union[str, None] = '274f6bf1b0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('accepted_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('primary_doc', sa.String(length=200), nullable=True),
    sa.Column('item_codes', sa.String(length=200), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('text_length', sa.String(length=20), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'accession_number', name='uq_cik_accession')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filings')
    # ### end Alembic commands ###
