"""add guardrail_json to investigations

Revision ID: 5a7d153c8fcd
Revises: e444965558cb
Create Date: 2026-08-09 18:50:43.221214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7d153c8fcd'
down_revision: Union[str, None] = 'e444965558cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('guardrail_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'guardrail_json')
    # ### end Alembic commands ###
