"""add analyst_feedback table

Revision ID: 7b92b54fdb0d
Revises: 5a7d153c8fcd
Create Date: 2026-08-11 20:55:37.386027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b92b54fdb0d'
down_revision: Union[str, None] = '5a7d153c8fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('original_value', sa.String(length=200), nullable=True),
    sa.Column('corrected_value', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyst_feedback')
    # ### end Alembic commands ###
