"""add event_entities table

Revision ID: a2ef5be8e3b7
Revises: 3ca47b4fe878
Create Date: 2026-08-06 18:33:32.347438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ef5be8e3b7'
down_revision: Union[str, None] = '3ca47b4fe878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filing_id', sa.String(length=50), nullable=False),
    sa.Column('matched_ticker', sa.String(length=10), nullable=False),
    sa.Column('extracted_text', sa.String(length=200), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_primary', sa.String(length=5), nullable=True),
    sa.Column('analyst_corrected', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_entities')
    # ### end Alembic commands ###
