"""add investigations table

Revision ID: e444965558cb
Revises: fa5f092a9bac
Create Date: 2026-08-09 17:53:44.118473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e444965558cb'
down_revision: Union[str, None] = 'fa5f092a9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('etf_ticker', sa.String(length=10), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_anomaly', sa.String(length=5), nullable=True),
    sa.Column('primary_driver', sa.String(length=200), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('attribution_json', sa.JSON(), nullable=True),
    sa.Column('anomaly_json', sa.JSON(), nullable=True),
    sa.Column('risk_decomposition_json', sa.JSON(), nullable=True),
    sa.Column('ranked_events_json', sa.JSON(), nullable=True),
    sa.Column('generated_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigations')
    # ### end Alembic commands ###
