"""add FinBERT sentiment probability columns

Revision ID: fa5f092a9bac
Revises: a2ef5be8e3b7
Create Date: 2026-08-08 20:29:10.198213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5f092a9bac'
down_revision: Union[str, None] = 'a2ef5be8e3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('sentiment_positive_prob', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('filings', sa.Column('sentiment_negative_prob', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('filings', sa.Column('sentiment_neutral_prob', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('filings', sa.Column('sentiment_model', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filings', 'sentiment_model')
    op.drop_column('filings', 'sentiment_neutral_prob')
    op.drop_column('filings', 'sentiment_negative_prob')
    op.drop_column('filings', 'sentiment_positive_prob')
    # ### end Alembic commands ###
